### PR TITLE
fix http_decoder.h ~ vlan_hdr.h

### PR DESCRIPTION
**Pull request by yuyashiraki**
Giwa san
Please review.

### CODE REVIEW

**Comment by yuyashiraki** [comment]
Giwa san

Sorry.
The last commit "fix /*" means "fix vlan_hdr.h".
And I think all of my works is done. Please review.

**Comment by giwa** [comment]
@yuyashiraki 
BTW you can change commit message.
```
git commit --amend -m "New commit message"
```

**Comment by giwa** [comment]
LGTM

**Comment by giwa** [comment]
close #79

**Pull request merged**
